[package]
name = "cork-hash"
edition.workspace = true
version.workspace = true

[dependencies]
sha2 = { workspace = true }

[dev-dependencies]
cork-canon = { workspace = true }
serde_json = { workspace = true }
