[package]
name = "cork-core"
edition.workspace = true
version.workspace = true

[[bin]]
name = "corkd"
path = "src/main.rs"

[dependencies]
cork-proto = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
